### PR TITLE
add LinearAccelerationTask and some more tests

### PR DESCRIPTION
**Pull request by rdeits**
Also adds tests for AngularAccelerationTask and LinearAccelerationTask by slightly modifying the existing SpatialAccelerationTask tests

### CODE REVIEW

**Comment by tkoolen** [comment]
Thanks!

So this currently adds a constraint on the linear component of a spatial acceleration. This might be confusing if `frame != bodyframe`. Should we just disallow that? Or do you really want a `PointAccelerationTask`?

**Comment by rdeits** [comment]
Ah, good point. This is probably still useful, but `PointAccelerationTask` is indeed what I actually want (since I'm actually trying to track position and velocity of a body expressed in world frame). I'm heading to lab now anyway, so we can discuss in person shortly.

**Comment by rdeits** [comment]
Ok, added PointAccelerationTask + tests and a new demo notebook

**Comment by tkoolen** [comment]
Looks great, thanks! I'd almost forgotten about `RigidBodyDynamics.simulate`, but it's pretty convenient for this :slightly_smiling_face:.

**Comment by rdeits** [comment]
Ok, travis is happy. Ready to merge?

**Comment by tkoolen** [comment]
Yup, thanks.

**Pull request merged**
